version: "3.3"
services:
  logstash-tcp-out:
    build: .
    ports:
      - 4888:4888
    volumes:
      - .:/tmp
  elk:
    image: sebp/elk
    environment:
      - ES_HEAP_SIZE=2g
      - MAX_MAP_COUNT=262144
      - ELASTICSEARCH_START=1
      - LOGSTASH_START=1
      - KIBANA_START=1
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "4718:4718"